/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bumarket.bumarket;

import java.awt.Color;

/**
 *
 * @author kritt
 */
public class Category extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
       lbId.setText(UserData.globalId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnProduct3 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnShoppingcart = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        txtProduct3 = new javax.swing.JLabel();
        txtprice3 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtProduct4 = new javax.swing.JLabel();
        txtprice4 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        txtProduct2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txtProduct1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        btnProduct1 = new javax.swing.JButton();
        txtProduct5 = new javax.swing.JLabel();
        txtProduct6 = new javax.swing.JLabel();
        txtProduct7 = new javax.swing.JLabel();
        txtProduct8 = new javax.swing.JLabel();
        txtProduct9 = new javax.swing.JLabel();
        txtProduct10 = new javax.swing.JLabel();
        btnProduct2 = new javax.swing.JButton();
        txtProduct11 = new javax.swing.JLabel();
        btnProduct4 = new javax.swing.JButton();
        btnPencil = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnPen = new javax.swing.JButton();
        btnOther = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Market Category");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 1194, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 3, 13, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("เครื่องเขียน");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 15, 138, 78));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ดินสอและไส้ดินสอ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("฿ 132.00");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        btnProduct3.setBackground(new java.awt.Color(204, 204, 204));
        btnProduct3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProduct3.setText("เพิ่มเติม");
        btnProduct3.setRequestFocusEnabled(false);
        btnProduct3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct33MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProduct3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProduct3MouseExited(evt);
            }
        });
        jPanel2.add(btnProduct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 156, 1200, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("(แพ็ค4แท่ง)");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        btnShoppingcart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnShoppingcart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2 (1).png"))); // NOI18N
        btnShoppingcart.setText("ประวัติการสั่งซื้อ");
        btnShoppingcart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnShoppingcart.setContentAreaFilled(false);
        btnShoppingcart.setRequestFocusEnabled(false);
        btnShoppingcart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShoppingcartMouseClicked(evt);
            }
        });
        jPanel2.add(btnShoppingcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 180, 50));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, -5, 16, 160));

        txtProduct3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct3.setText("ควอนตั้ม QP-920");
        txtProduct3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct3.setVerifyInputWhenFocusTarget(false);
        txtProduct3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        txtprice3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprice3.setForeground(new java.awt.Color(255, 0, 0));
        txtprice3.setText("฿ 119.00");
        jPanel2.add(txtprice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 200, 10));

        txtProduct4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct4.setText("100-4H สีน้ำเงิน");
        txtProduct4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct4.setVerifyInputWhenFocusTarget(false);
        txtProduct4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, -1, -1));

        txtprice4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprice4.setForeground(new java.awt.Color(255, 0, 0));
        txtprice4.setText("฿ 24.00");
        jPanel2.add(txtprice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, -1, -1));

        jSeparator14.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 200, 10));

        txtProduct2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct2.setText("ด้ามสีขาว");
        txtProduct2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct2.setVerifyInputWhenFocusTarget(false);
        txtProduct2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 190, -1));

        jSeparator10.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 200, 10));

        txtProduct1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pencil4.jpg"))); // NOI18N
        txtProduct1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct1.setVerifyInputWhenFocusTarget(false);
        txtProduct1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        txtProduct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProduct1MouseClicked(evt);
            }
        });
        jPanel2.add(txtProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 190, -1));

        jSeparator9.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 190, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("฿ 45.00");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        btnProduct1.setBackground(new java.awt.Color(204, 204, 204));
        btnProduct1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProduct1.setText("เพิ่มเติม");
        btnProduct1.setRequestFocusEnabled(false);
        btnProduct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProduct1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProduct1MouseExited(evt);
            }
        });
        jPanel2.add(btnProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        txtProduct5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct5.setText("ดินสอดำ 2B (กล่อง12แท่ง)");
        txtProduct5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct5.setVerifyInputWhenFocusTarget(false);
        txtProduct5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        txtProduct6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct6.setText("ดินสอกด 0.5 มม. Rotring Tikky ");
        txtProduct6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct6.setVerifyInputWhenFocusTarget(false);
        txtProduct6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 190, -1));

        txtProduct7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct7.setText("ROTRING ดินสอไม้ HB Metallic คละสี");
        txtProduct7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct7.setVerifyInputWhenFocusTarget(false);
        txtProduct7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 220, -1));

        txtProduct8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pencil1.jpg"))); // NOI18N
        txtProduct8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct8.setVerifyInputWhenFocusTarget(false);
        txtProduct8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        txtProduct8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProduct8MouseClicked(evt);
            }
        });
        jPanel2.add(txtProduct8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 190, -1));

        txtProduct9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pencil2.jpg"))); // NOI18N
        txtProduct9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct9.setVerifyInputWhenFocusTarget(false);
        txtProduct9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        txtProduct9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProduct9MouseClicked(evt);
            }
        });
        jPanel2.add(txtProduct9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 190, -1));

        txtProduct10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pencil3.jpg"))); // NOI18N
        txtProduct10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct10.setVerifyInputWhenFocusTarget(false);
        txtProduct10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        txtProduct10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProduct10MouseClicked(evt);
            }
        });
        jPanel2.add(txtProduct10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 190, -1));

        btnProduct2.setBackground(new java.awt.Color(204, 204, 204));
        btnProduct2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProduct2.setText("เพิ่มเติม");
        btnProduct2.setRequestFocusEnabled(false);
        btnProduct2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProduct2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProduct2MouseExited(evt);
            }
        });
        jPanel2.add(btnProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        txtProduct11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct11.setText("ดินสอเขียนแบบลูโมกราฟ สเต็ดเล่อร์ ");
        txtProduct11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct11.setVerifyInputWhenFocusTarget(false);
        txtProduct11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, -1, -1));

        btnProduct4.setBackground(new java.awt.Color(204, 204, 204));
        btnProduct4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProduct4.setText("เพิ่มเติม");
        btnProduct4.setRequestFocusEnabled(false);
        btnProduct4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct43MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProduct4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProduct4MouseExited(evt);
            }
        });
        jPanel2.add(btnProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, -1, -1));

        btnPencil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPencil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil.png"))); // NOI18N
        btnPencil.setText("ดินสอและไส้ดินสอ");
        btnPencil.setBorder(null);
        btnPencil.setContentAreaFilled(false);
        btnPencil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPencil.setIconTextGap(0);
        btnPencil.setRequestFocusEnabled(false);
        btnPencil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPencil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPencilMouseClicked(evt);
            }
        });
        jPanel2.add(btnPencil, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 15, 118, 78));

        btnBook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        btnBook.setText("สมุด");
        btnBook.setBorder(null);
        btnBook.setContentAreaFilled(false);
        btnBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBook.setIconTextGap(0);
        btnBook.setMaximumSize(new java.awt.Dimension(118, 78));
        btnBook.setMinimumSize(new java.awt.Dimension(118, 78));
        btnBook.setPreferredSize(new java.awt.Dimension(118, 78));
        btnBook.setRequestFocusEnabled(false);
        btnBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBookMouseClicked(evt);
            }
        });
        jPanel2.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 15, 118, -1));

        btnPen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pen.png"))); // NOI18N
        btnPen.setText("ปากกา");
        btnPen.setBorder(null);
        btnPen.setContentAreaFilled(false);
        btnPen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPen.setIconTextGap(0);
        btnPen.setMaximumSize(new java.awt.Dimension(118, 78));
        btnPen.setMinimumSize(new java.awt.Dimension(118, 78));
        btnPen.setPreferredSize(new java.awt.Dimension(118, 78));
        btnPen.setRequestFocusEnabled(false);
        btnPen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPenMouseClicked(evt);
            }
        });
        jPanel2.add(btnPen, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 15, 118, 78));

        btnOther.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOther.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mais-1.png"))); // NOI18N
        btnOther.setText("อื่นๆ");
        btnOther.setBorder(null);
        btnOther.setContentAreaFilled(false);
        btnOther.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOther.setIconTextGap(0);
        btnOther.setMaximumSize(new java.awt.Dimension(118, 78));
        btnOther.setMinimumSize(new java.awt.Dimension(118, 78));
        btnOther.setPreferredSize(new java.awt.Dimension(118, 78));
        btnOther.setRequestFocusEnabled(false);
        btnOther.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOther.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOtherMouseClicked(evt);
            }
        });
        jPanel2.add(btnOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 15, 118, 78));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 564));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_logo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 120, 110));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 37, -1, 30));

        txtSearch.setBackground(new java.awt.Color(216, 216, 216));
        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearch.setText("  Search");
        txtSearch.setToolTipText("");
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 35, 410, 34));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopicon.png"))); // NOI18N
        jLabel11.setRequestFocusEnabled(false);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 35, 50, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("My Account");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 35, -1, -1));

        lbId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbId.setForeground(new java.awt.Color(255, 255, 255));
        lbId.setText("XXXXX XXXXX");
        jPanel1.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 55, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit.png"))); // NOI18N
        lbLogout.setRequestFocusEnabled(false);
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 40, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusable(false);
        btnBack.setRequestFocusEnabled(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Up.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void btnProduct33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct33MouseClicked
        new MarketPencil4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProduct33MouseClicked

    private void btnProduct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct1MouseClicked

    private void btnProduct2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct2MouseClicked
        // TODO add your handling code here:
        new MarketPencil2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProduct2MouseClicked

    private void btnProduct43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct43MouseClicked
        // TODO add your handling code here:
        new MarketPencil3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProduct43MouseClicked

    private void btnPencilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPencilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPencilMouseClicked

    private void btnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookMouseClicked
        // TODO add your handling code here:
        new Category2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookMouseClicked

    private void btnOtherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOtherMouseClicked
        // TODO add your handling code here:
        new Category4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOtherMouseClicked

    private void btnPenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenMouseClicked
        // TODO add your handling code here:
        new Category3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPenMouseClicked

    private void btnProduct4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct4MouseEntered
        btnProduct4.setBackground(Color.red);
        btnProduct4.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnProduct4MouseEntered

    private void btnProduct1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct1MouseEntered
        btnProduct1.setBackground(Color.red);
        btnProduct1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnProduct1MouseEntered

    private void btnProduct1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct1MouseExited
        btnProduct1.setBackground(new Color(204,204,204));
        btnProduct1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnProduct1MouseExited

    private void txtProduct8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProduct8MouseClicked
        new MarketPencil1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtProduct8MouseClicked

    private void txtProduct9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProduct9MouseClicked
       new MarketPencil2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtProduct9MouseClicked

    private void txtProduct10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProduct10MouseClicked
        new MarketPencil3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtProduct10MouseClicked

    private void txtProduct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProduct1MouseClicked
       new MarketPencil4().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_txtProduct1MouseClicked

    private void btnProduct2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct2MouseEntered
        btnProduct2.setBackground(Color.red);
        btnProduct2.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnProduct2MouseEntered

    private void btnProduct2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct2MouseExited
        btnProduct2.setBackground(new Color(204,204,204));
        btnProduct2.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnProduct2MouseExited

    private void btnProduct4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct4MouseExited
        btnProduct4.setBackground(new Color(204,204,204));
        btnProduct4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnProduct4MouseExited

    private void btnProduct3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct3MouseEntered
        btnProduct3.setBackground(Color.red);
        btnProduct3.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnProduct3MouseEntered

    private void btnProduct3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct3MouseExited
        btnProduct3.setBackground(new Color(204,204,204));
        btnProduct3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnProduct3MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new Shoppingcart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnShoppingcartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShoppingcartMouseClicked
        // TODO add your handling code here:
        new Checkout().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnShoppingcartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnOther;
    private javax.swing.JButton btnPen;
    private javax.swing.JButton btnPencil;
    private javax.swing.JButton btnProduct1;
    private javax.swing.JButton btnProduct2;
    private javax.swing.JButton btnProduct3;
    private javax.swing.JButton btnProduct4;
    private javax.swing.JButton btnShoppingcart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel txtProduct1;
    private javax.swing.JLabel txtProduct10;
    private javax.swing.JLabel txtProduct11;
    private javax.swing.JLabel txtProduct2;
    private javax.swing.JLabel txtProduct3;
    private javax.swing.JLabel txtProduct4;
    private javax.swing.JLabel txtProduct5;
    private javax.swing.JLabel txtProduct6;
    private javax.swing.JLabel txtProduct7;
    private javax.swing.JLabel txtProduct8;
    private javax.swing.JLabel txtProduct9;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtprice3;
    private javax.swing.JLabel txtprice4;
    // End of variables declaration//GEN-END:variables
}
