/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bumarket.bumarket;

/**
 *
 * @author USER
 */
public class Categoryjacket extends javax.swing.JFrame {

    /**
     * Creates new form Categoryjacket
     */
    public Categoryjacket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        btnShirt = new javax.swing.JButton();
        btnUniform = new javax.swing.JButton();
        btnJackets = new javax.swing.JButton();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        btnPoint = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtProduct1 = new javax.swing.JLabel();
        txtprice1 = new javax.swing.JLabel();
        txtProduct2 = new javax.swing.JLabel();
        txtprice2 = new javax.swing.JLabel();
        txtProduct3 = new javax.swing.JLabel();
        txtprice3 = new javax.swing.JLabel();
        txtProduct4 = new javax.swing.JLabel();
        txtprice4 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        btnProduct1 = new javax.swing.JButton();
        btnProduct2 = new javax.swing.JButton();
        btnProduct4 = new javax.swing.JButton();
        btnProduct3 = new javax.swing.JButton();
        iconUniversity = new javax.swing.JLabel();
        txtGlass = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        Cart = new javax.swing.JLabel();
        txtAccount = new javax.swing.JLabel();
        txtUSER = new javax.swing.JLabel();
        iconUSER = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 1194, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 3, 13, 100));

        jSeparator12.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 156, 1200, 10));

        btnShirt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnShirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon1 (2).png"))); // NOI18N
        btnShirt.setText("เสื้อผ้า");
        btnShirt.setBorder(null);
        btnShirt.setContentAreaFilled(false);
        btnShirt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShirt.setIconTextGap(0);
        btnShirt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShirtActionPerformed(evt);
            }
        });
        jPanel2.add(btnShirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 110, 110));

        btnUniform.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUniform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled (4).png"))); // NOI18N
        btnUniform.setText("ชุดนักศึกษา");
        btnUniform.setBorder(null);
        btnUniform.setContentAreaFilled(false);
        btnUniform.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUniform.setIconTextGap(0);
        btnUniform.setMaximumSize(new java.awt.Dimension(118, 78));
        btnUniform.setMinimumSize(new java.awt.Dimension(118, 78));
        btnUniform.setPreferredSize(new java.awt.Dimension(118, 78));
        btnUniform.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUniform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUniformMouseClicked(evt);
            }
        });
        btnUniform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniformActionPerformed(evt);
            }
        });
        jPanel2.add(btnUniform, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 130, 120));

        btnJackets.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnJackets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconjacket (1).png"))); // NOI18N
        btnJackets.setText("เสื้อแจ็คเก็ต");
        btnJackets.setBorder(null);
        btnJackets.setContentAreaFilled(false);
        btnJackets.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJackets.setIconTextGap(0);
        btnJackets.setMaximumSize(new java.awt.Dimension(118, 78));
        btnJackets.setMinimumSize(new java.awt.Dimension(118, 78));
        btnJackets.setPreferredSize(new java.awt.Dimension(118, 78));
        btnJackets.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnJackets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJacketsMouseClicked(evt);
            }
        });
        btnJackets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJacketsActionPerformed(evt);
            }
        });
        jPanel2.add(btnJackets, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 118, 90));

        txt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt1.setText("เสื้อแจ็คเก็ต");
        jPanel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 15, 138, 78));

        txt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt2.setText("เสื้อแจ็คเก็ต");
        jPanel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btnPoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2 (1).png"))); // NOI18N
        btnPoint.setText("ยอดพอยท์คงเหลือ");
        btnPoint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPoint.setContentAreaFilled(false);
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });
        jPanel2.add(btnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 180, 49));

        btnHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2 (1).png"))); // NOI18N
        btnHistory.setText("ประวัติการสั่งซื้อ");
        btnHistory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistory.setContentAreaFilled(false);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        jPanel2.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 180, 50));

        jSeparator8.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 200, 10));

        jSeparator9.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 180, 10));

        txtProduct1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct1.setText("เสื้อแจ็คเก็ต สำหรับเดินป่า");
        txtProduct1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct1.setVerifyInputWhenFocusTarget(false);
        txtProduct1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 190, -1));

        txtprice1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprice1.setForeground(new java.awt.Color(255, 0, 0));
        txtprice1.setText("฿ 389.00");
        jPanel2.add(txtprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        txtProduct2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct2.setText("เสื้อแจ็คเก็ตแฟชั่นสไตล์เกาหลี");
        txtProduct2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct2.setVerifyInputWhenFocusTarget(false);
        txtProduct2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 180, -1));

        txtprice2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprice2.setForeground(new java.awt.Color(255, 0, 0));
        txtprice2.setText("฿ 274.00");
        jPanel2.add(txtprice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        txtProduct3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct3.setText("เสื้อแจ็กเก็ตกันหนาว ผ้าฟลีซ");
        txtProduct3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct3.setVerifyInputWhenFocusTarget(false);
        txtProduct3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        txtprice3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprice3.setForeground(new java.awt.Color(255, 0, 0));
        txtprice3.setText("฿ 307.00");
        jPanel2.add(txtprice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        txtProduct4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduct4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtProduct4.setText("เสื้อแจ็คเก็ตแขนยาวผู้ชาย");
        txtProduct4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtProduct4.setVerifyInputWhenFocusTarget(false);
        txtProduct4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, -1, -1));

        txtprice4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtprice4.setForeground(new java.awt.Color(255, 0, 0));
        txtprice4.setText("฿ 411.00");
        jPanel2.add(txtprice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 200, 10));

        jSeparator13.setForeground(new java.awt.Color(121, 121, 121));
        jSeparator13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 200, 10));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, -5, 16, 160));

        btnProduct1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jacket1.jpg"))); // NOI18N
        btnProduct1.setBorder(null);
        btnProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 190));

        btnProduct2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jacket2.jpg"))); // NOI18N
        btnProduct2.setBorder(null);
        jPanel2.add(btnProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 190, 190));

        btnProduct4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jacket4.jpg"))); // NOI18N
        btnProduct4.setBorder(null);
        jPanel2.add(btnProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 190, 190));

        btnProduct3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jacket3.jpg"))); // NOI18N
        btnProduct3.setBorder(null);
        jPanel2.add(btnProduct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 190, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 500));

        iconUniversity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_logo.png"))); // NOI18N
        jPanel1.add(iconUniversity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 120, 110));

        txtGlass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        jPanel1.add(txtGlass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 37, -1, 30));

        txtSearch.setBackground(new java.awt.Color(216, 216, 216));
        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearch.setText("  Search");
        txtSearch.setToolTipText("");
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 35, 410, 34));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, 60, 40));

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopicon.png"))); // NOI18N
        jPanel1.add(Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 35, 50, 40));

        txtAccount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAccount.setForeground(new java.awt.Color(255, 255, 255));
        txtAccount.setText("My Account");
        jPanel1.add(txtAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 35, -1, -1));

        txtUSER.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUSER.setForeground(new java.awt.Color(255, 255, 255));
        txtUSER.setText("XXXXX XXXXX");
        jPanel1.add(txtUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 55, -1, -1));

        iconUSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account.png"))); // NOI18N
        jPanel1.add(iconUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setContentAreaFilled(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Up.png"))); // NOI18N
        background.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShirtActionPerformed
         new CategoryStudent().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnShirtActionPerformed

    private void btnUniformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUniformMouseClicked
        new Category2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUniformMouseClicked

    private void btnUniformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniformActionPerformed
         new Categoryshirt().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnUniformActionPerformed

    private void btnJacketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJacketsMouseClicked
        new Category3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJacketsMouseClicked

    private void btnJacketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJacketsActionPerformed
         new Categoryjacket().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnJacketsActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct1ActionPerformed
        new MarketJacket1().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnProduct1ActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
         new Shoppingcart().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categoryjacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categoryjacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categoryjacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categoryjacket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categoryjacket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cart;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnJackets;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnProduct1;
    private javax.swing.JButton btnProduct2;
    private javax.swing.JButton btnProduct3;
    private javax.swing.JButton btnProduct4;
    private javax.swing.JButton btnShirt;
    private javax.swing.JButton btnUniform;
    private javax.swing.JLabel iconUSER;
    private javax.swing.JLabel iconUniversity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txtAccount;
    private javax.swing.JLabel txtGlass;
    private javax.swing.JLabel txtProduct1;
    private javax.swing.JLabel txtProduct2;
    private javax.swing.JLabel txtProduct3;
    private javax.swing.JLabel txtProduct4;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtUSER;
    private javax.swing.JLabel txtprice1;
    private javax.swing.JLabel txtprice2;
    private javax.swing.JLabel txtprice3;
    private javax.swing.JLabel txtprice4;
    // End of variables declaration//GEN-END:variables
}
