/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bumarket.bumarket;

import javax.swing.JOptionPane;

/**
 *
 * @author pongs
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loadbar = new javax.swing.JProgressBar();
        Loadvalue = new javax.swing.JLabel();
        loadlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loadbar.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Loadbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1280, 10));

        Loadvalue.setBackground(new java.awt.Color(255, 255, 255));
        Loadvalue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Loadvalue.setText("0%");
        getContentPane().add(Loadvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 680, 40, -1));

        loadlabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        loadlabel.setForeground(new java.awt.Color(255, 255, 255));
        loadlabel.setText("Loading....");
        getContentPane().add(loadlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Download.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Loading load = new Loading();
        load.setVisible(true);
        Login login = new Login();
        try 
            {
                for(int i=0;i<=100;i++){
                   Thread.sleep(100);
                   load.Loadvalue.setText(i +"%");
                   
                   if(i==10)
                   {
                        load.loadlabel.setText ("Turning 0n Modulea...");
                   }
                   if(i==20)
                   {
                       load.loadlabel.setText ("loading Modules...");
                   }
                   if(i==50)
                   {
                       load.loadlabel.setText ("Connecting to Database...");
                   }

                   if (1==70){
                       load.loadlabel.setText("Connection Successful !");
                   }
                   if(i==80){
                       load.loadlabel.setText ("Launching Webpage...");
                   }
                   load.Loadbar.setValue(i);
                }
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            load.setVisible(false);
            login.setVisible(true);
            load.dispose();
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar Loadbar;
    public static javax.swing.JLabel Loadvalue;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel loadlabel;
    // End of variables declaration//GEN-END:variables
}
