/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bumarket.bumarket;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author chait
 */
public class Login extends javax.swing.JFrame {

    private final UserData userdata;
    
    public Login() {
        initComponents();
        userdata = new UserData();
        eye_hide.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        eye_hide = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        SignUpBtn = new javax.swing.JButton();
        ConfirmBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ForgetPassBtn = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(202, 202, 202));
        jPanel6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eye_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png"))); // NOI18N
        eye_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eye_hideMousePressed(evt);
            }
        });
        jPanel6.add(eye_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 85, -1, -1));

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eyeMousePressed(evt);
            }
        });
        jPanel6.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 85, -1, -1));

        txtUser.setBackground(new java.awt.Color(202, 202, 202));
        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(119, 119, 119));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUser.setText("Username");
        txtUser.setBorder(null);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        jPanel6.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, -1));

        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator29.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel6.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 252, 10));

        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator28.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel6.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 252, 10));

        SignUpBtn.setBackground(new java.awt.Color(208, 204, 204));
        SignUpBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(255, 153, 0));
        SignUpBtn.setText("Register");
        SignUpBtn.setBorder(null);
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });
        jPanel6.add(SignUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        ConfirmBtn.setBackground(new java.awt.Color(0, 0, 0));
        ConfirmBtn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setText("Login");
        ConfirmBtn.setBorderPainted(false);
        ConfirmBtn.setRequestFocusEnabled(false);
        ConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtnActionPerformed(evt);
            }
        });
        jPanel6.add(ConfirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 192, 56));

        jLabel3.setForeground(new java.awt.Color(119, 119, 119));
        jLabel3.setText("Don't have an Account ? ");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        ForgetPassBtn.setBackground(new java.awt.Color(208, 204, 204));
        ForgetPassBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ForgetPassBtn.setForeground(new java.awt.Color(255, 153, 0));
        ForgetPassBtn.setText("Change Password");
        ForgetPassBtn.setBorder(null);
        ForgetPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetPassBtnActionPerformed(evt);
            }
        });
        jPanel6.add(ForgetPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtPass.setBackground(new java.awt.Color(202, 202, 202));
        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(119, 119, 119));
        txtPass.setText("Password");
        txtPass.setBorder(null);
        txtPass.setEchoChar('\u0000');
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        jPanel6.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, 210, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 270, 300));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BU MARKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2.2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 160, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUpBtnActionPerformed

    private void ForgetPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetPassBtnActionPerformed
        new Change_pass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ForgetPassBtnActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
       if(txtUser.getText().equals("Username"))
       {
           txtUser.setText("");
       }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if (txtUser.getText().length()==0)
            txtUser.setText("Username");
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        if(txtPass.getText().equals("Password"))
       {
           txtPass.setText("");
       }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        if (txtPass.getText().length()==0)
            txtPass.setText("Password");
    }//GEN-LAST:event_txtPassFocusLost

    private void eye_hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_hideMousePressed
        eye_hide.setVisible(false);
        eye.setVisible(true);
        txtPass.setEchoChar((char)0);
    }//GEN-LAST:event_eye_hideMousePressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void eyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMousePressed
        eye.setVisible(false);
        eye_hide.setVisible(true);
        txtPass.setEchoChar('*');
    }//GEN-LAST:event_eyeMousePressed

    private void ConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtnActionPerformed
        userdata.getUsers();
        String username = txtUser.getText().trim();
        String password = String.valueOf(txtPass.getPassword()).trim();
        boolean userExist = false;
        try {
            if(username.equals("Username") || password.equals("Password")) {
                JOptionPane.showMessageDialog(this, "One or Both fields are Empty", "Info", JOptionPane.INFORMATION_MESSAGE);
                txtPass.requestFocus();
            }
            else { 
                for(String uname: userdata.usernameANDpassword.keySet()) {
                    System.out.println(uname);
                    if(uname.equals(username)) {
                        if(userdata.usernameANDpassword.get(uname).equals(password)) {
                            userdata.checkId(username);
                            userdata.globalId = userdata.usernameANDId.get(uname);
                            System.out.println(userdata.globalId);
                            userExist = true;
                            System.out.println("Welcome To The Application");
                            new Home().setVisible(true);
                            this.dispose();
                            break;
                            }
                        }
                    }
                if(userExist == false) {
                    JOptionPane.showMessageDialog(this, "Wrong Username or Password!", "Error", JOptionPane.ERROR_MESSAGE);
                    txtPass.requestFocus();
                }
            }
        } catch (Exception e) {
            System.out.println("Failed to Login");
        }
    }//GEN-LAST:event_ConfirmBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JButton ForgetPassBtn;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel eye_hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
