/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bumarket.bumarket;

import javax.swing.JOptionPane;

/**
 *
 * @author chait
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        txtUser3 = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        txtNewPwd3 = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        SignInBtn3 = new javax.swing.JButton();
        ConfirmBtn3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SignInBtn4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(202, 202, 202));
        jPanel6.setForeground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser3.setBackground(new java.awt.Color(202, 202, 202));
        txtUser3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUser3.setForeground(new java.awt.Color(119, 119, 119));
        txtUser3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUser3.setText("Username");
        txtUser3.setBorder(null);
        jPanel6.add(txtUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 271, -1));

        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator29.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel6.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 252, 10));

        txtNewPwd3.setBackground(new java.awt.Color(202, 202, 202));
        txtNewPwd3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNewPwd3.setForeground(new java.awt.Color(119, 119, 119));
        txtNewPwd3.setText("Password");
        txtNewPwd3.setBorder(null);
        txtNewPwd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPwd3ActionPerformed(evt);
            }
        });
        jPanel6.add(txtNewPwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 265, -1));

        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator28.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jPanel6.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 252, 10));

        SignInBtn3.setBackground(new java.awt.Color(208, 204, 204));
        SignInBtn3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SignInBtn3.setForeground(new java.awt.Color(255, 153, 0));
        SignInBtn3.setText("Register");
        SignInBtn3.setBorder(null);
        SignInBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInBtn3SignInBtnMouseClicked(evt);
            }
        });
        SignInBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtn3ActionPerformed(evt);
            }
        });
        jPanel6.add(SignInBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        ConfirmBtn3.setBackground(new java.awt.Color(0, 0, 0));
        ConfirmBtn3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ConfirmBtn3.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmBtn3.setText("Login");
        ConfirmBtn3.setBorderPainted(false);
        ConfirmBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmBtn3ConfirmBtnMouseClicked(evt);
            }
        });
        ConfirmBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBtn3ActionPerformed(evt);
            }
        });
        jPanel6.add(ConfirmBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 192, 56));

        jLabel3.setText("Don't have a Account ? ");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        SignInBtn4.setBackground(new java.awt.Color(208, 204, 204));
        SignInBtn4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SignInBtn4.setForeground(new java.awt.Color(255, 153, 0));
        SignInBtn4.setText("Forget Password ?");
        SignInBtn4.setBorder(null);
        SignInBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInBtn4SignInBtnMouseClicked(evt);
            }
        });
        SignInBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtn4ActionPerformed(evt);
            }
        });
        jPanel6.add(SignInBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 270, 300));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BU MARKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2.2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 160, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBtn3ConfirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmBtn3ConfirmBtnMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Password has been changed.");
    }//GEN-LAST:event_ConfirmBtn3ConfirmBtnMouseClicked

    private void SignInBtn3SignInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInBtn3SignInBtnMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignInBtn3SignInBtnMouseClicked

    private void SignInBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtn3ActionPerformed
        new Register().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SignInBtn3ActionPerformed

    private void SignInBtn4SignInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInBtn4SignInBtnMouseClicked
        new Forget_Pwd().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SignInBtn4SignInBtnMouseClicked

    private void SignInBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInBtn4ActionPerformed

    private void txtNewPwd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPwd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPwd3ActionPerformed

    private void ConfirmBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBtn3ActionPerformed
         new Home().setVisible(true);
         this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBtn3;
    private javax.swing.JButton ForgetBtn;
    private javax.swing.JButton ForgetBtn1;
    private javax.swing.JButton ForgetBtn2;
    private javax.swing.JButton ForgetBtn3;
    private javax.swing.JButton ForgetBtn4;
    private javax.swing.JButton ForgetBtn5;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton LoginBtn1;
    private javax.swing.JButton LoginBtn2;
    private javax.swing.JButton LoginBtn3;
    private javax.swing.JButton LoginBtn4;
    private javax.swing.JButton LoginBtn5;
    private javax.swing.JButton SignInBtn3;
    private javax.swing.JButton SignInBtn4;
    private javax.swing.JButton SignupBtn;
    private javax.swing.JButton SignupBtn1;
    private javax.swing.JButton SignupBtn2;
    private javax.swing.JButton SignupBtn3;
    private javax.swing.JButton SignupBtn4;
    private javax.swing.JButton SignupBtn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField txtNewPwd3;
    private javax.swing.JTextField txtUser3;
    // End of variables declaration//GEN-END:variables
}
