/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bumarket.bumarket;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MarketShirt2 extends javax.swing.JFrame {

    /**
     * Creates new form MarketShirt2
     */
    public MarketShirt2() {
        initComponents();
        txtUSER.setText(UserData.globalId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconUniversity = new javax.swing.JLabel();
        txtAccount = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtProduct = new javax.swing.JLabel();
        txtDescription = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        txtColor = new javax.swing.JLabel();
        btnBlack = new javax.swing.JButton();
        btnWhite = new javax.swing.JButton();
        txtSize = new javax.swing.JLabel();
        btnSizeM = new javax.swing.JButton();
        btnSizeL = new javax.swing.JButton();
        btnSizeXL = new javax.swing.JButton();
        btnSize2XL = new javax.swing.JButton();
        txtAmount = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Productshirt1 = new javax.swing.JLabel();
        Productshirt2 = new javax.swing.JLabel();
        Productshirt3 = new javax.swing.JLabel();
        Productshirt4 = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        btnAdd_to_cart = new javax.swing.JButton();
        txtUSER = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        Cart = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtGlass = new javax.swing.JLabel();
        iconUSER = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Market");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconUniversity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_logo.png"))); // NOI18N
        getContentPane().add(iconUniversity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 120, 110));

        txtAccount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAccount.setForeground(new java.awt.Color(255, 255, 255));
        txtAccount.setText("My Account");
        getContentPane().add(txtAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 35, -1, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProduct.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtProduct.setText("เสื้อเชิ้ตลำลอง แขนยาวผ้าฝ้าย");
        jPanel1.add(txtProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 570, 40));

        txtDescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDescription.setText("คำอธิบาย");
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 80, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt2.setText("เนื้อผ้าเบาใส่สบาย");
        jPanel3.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, -1));

        txt3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt3.setText("ใส่ได้ทุกโอกาส");
        jPanel3.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, 20));

        txt4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt4.setText("ไม่หด ไม่ย้วย ดูแลรักษาง่าย ซักได้ทั้งเครื่อง และ มือ");
        jPanel3.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 450, -1));

        txt5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt5.setText("เนื้อผ้าเบา สวมใส่สบาย ซับเหงื่อ");
        jPanel3.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 450, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 510, 190));

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(204, 0, 0));
        txtPrice.setText("฿198.00");
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 100, 40));

        txtColor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtColor.setText("สี");
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 20, 30));

        btnBlack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBlack.setText("สีดำ");
        btnBlack.setContentAreaFilled(false);
        btnBlack.setFocusPainted(false);
        btnBlack.setFocusable(false);
        btnBlack.setRequestFocusEnabled(false);
        jPanel1.add(btnBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, 30));

        btnWhite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnWhite.setText("สีขาว");
        btnWhite.setContentAreaFilled(false);
        btnWhite.setFocusPainted(false);
        btnWhite.setFocusable(false);
        btnWhite.setRequestFocusEnabled(false);
        jPanel1.add(btnWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, 30));

        txtSize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSize.setText("ขนาด");
        jPanel1.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 50, 30));

        btnSizeM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSizeM.setText("M");
        btnSizeM.setContentAreaFilled(false);
        btnSizeM.setFocusPainted(false);
        btnSizeM.setFocusable(false);
        btnSizeM.setRequestFocusEnabled(false);
        jPanel1.add(btnSizeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 50, 30));

        btnSizeL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSizeL.setText("L");
        btnSizeL.setContentAreaFilled(false);
        btnSizeL.setFocusPainted(false);
        btnSizeL.setFocusable(false);
        btnSizeL.setRequestFocusEnabled(false);
        jPanel1.add(btnSizeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 50, 30));

        btnSizeXL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSizeXL.setText("XL");
        btnSizeXL.setContentAreaFilled(false);
        btnSizeXL.setFocusPainted(false);
        btnSizeXL.setFocusable(false);
        btnSizeXL.setRequestFocusEnabled(false);
        jPanel1.add(btnSizeXL, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 50, 30));

        btnSize2XL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSize2XL.setText("2XL");
        btnSize2XL.setContentAreaFilled(false);
        btnSize2XL.setFocusPainted(false);
        btnSize2XL.setFocusable(false);
        btnSize2XL.setRequestFocusEnabled(false);
        jPanel1.add(btnSize2XL, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 60, 30));

        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAmount.setText("จำนวน");
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 70, 30));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 120, 30));

        Productshirt1.setBackground(new java.awt.Color(204, 204, 204));
        Productshirt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shirt2.1.jpg"))); // NOI18N
        Productshirt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Productshirt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Productshirt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 280, 280));

        Productshirt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shirt2.2.jpg"))); // NOI18N
        jPanel1.add(Productshirt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 90, -1));

        Productshirt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shirt2.3.jpg"))); // NOI18N
        jPanel1.add(Productshirt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        Productshirt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shirt2.4.jpg"))); // NOI18N
        jPanel1.add(Productshirt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 80, -1));

        btnBuy.setBackground(new java.awt.Color(204, 204, 204));
        btnBuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuy.setText("ซื้อสินค้า");
        btnBuy.setFocusPainted(false);
        btnBuy.setFocusable(false);
        btnBuy.setRequestFocusEnabled(false);
        btnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuyMouseExited(evt);
            }
        });
        jPanel1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 140, 40));

        btnAdd_to_cart.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd_to_cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd_to_cart.setText("หยิบใส่ตระกร้า");
        btnAdd_to_cart.setFocusPainted(false);
        btnAdd_to_cart.setFocusable(false);
        btnAdd_to_cart.setRequestFocusEnabled(false);
        btnAdd_to_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd_to_cartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd_to_cartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd_to_cartMouseExited(evt);
            }
        });
        jPanel1.add(btnAdd_to_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 1090, 540));

        txtUSER.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUSER.setForeground(new java.awt.Color(255, 255, 255));
        txtUSER.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUSER.setText("XXXXX XXXXX");
        getContentPane().add(txtUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, -1, 20));

        txtSearch.setBackground(new java.awt.Color(216, 216, 216));
        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearch.setText("  Search");
        txtSearch.setToolTipText("");
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 35, 410, 30));

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shopicon.png"))); // NOI18N
        Cart.setRequestFocusEnabled(false);
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMouseClicked(evt);
            }
        });
        getContentPane().add(Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 35, 50, 40));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setContentAreaFilled(false);
        btnBack.setRequestFocusEnabled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 80));

        txtGlass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        getContentPane().add(txtGlass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 37, -1, 30));

        iconUSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account.png"))); // NOI18N
        getContentPane().add(iconUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, 70));

        lbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit.png"))); // NOI18N
        lbLogout.setRequestFocusEnabled(false);
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(lbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 40, -1, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Up.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseClicked
        ProductData user = new ProductData();
        user.setProduct("เสื้อเชิ้ตลำลอง แขนยาวผ้าฝ้าย ");
        user.setQty(((Number) jSpinner1.getValue()).intValue());
        user.setPrice(198.00);
        user.setTotal(user.getPrice() * user.getQty());

        ProductList.cart1.add(user);

        JOptionPane.showMessageDialog(this,"Save Completed...");
        new Shoppingcart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuyMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Categoryshirt().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbLogoutMouseClicked

    private void btnBuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseEntered
        btnBuy.setBackground(Color.red);
        btnBuy.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBuyMouseEntered

    private void btnBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseExited
        btnBuy.setBackground(new Color(204,204,204));
        btnBuy.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnBuyMouseExited

    private void btnAdd_to_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_to_cartMouseClicked
        ProductData user = new ProductData();
        user.setProduct("เสื้อเชิ้ตลำลอง แขนยาวผ้าฝ้าย ");
        user.setQty(((Number) jSpinner1.getValue()).intValue());
        user.setPrice(198.00);
        user.setTotal(user.getPrice() * user.getQty());

        ProductList.cart1.add(user);

        JOptionPane.showMessageDialog(this,"Save Completed...");
        //new History().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnAdd_to_cartMouseClicked

    private void btnAdd_to_cartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_to_cartMouseEntered
        btnAdd_to_cart.setBackground(Color.red);
        btnAdd_to_cart.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAdd_to_cartMouseEntered

    private void btnAdd_to_cartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_to_cartMouseExited
        btnAdd_to_cart.setBackground(new Color(204,204,204));
        btnAdd_to_cart.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnAdd_to_cartMouseExited

    private void CartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMouseClicked
        new Shoppingcart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketShirt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketShirt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketShirt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketShirt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketShirt2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cart;
    private javax.swing.JLabel Productshirt1;
    private javax.swing.JLabel Productshirt2;
    private javax.swing.JLabel Productshirt3;
    private javax.swing.JLabel Productshirt4;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAdd_to_cart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBlack;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnSize2XL;
    private javax.swing.JButton btnSizeL;
    private javax.swing.JButton btnSizeM;
    private javax.swing.JButton btnSizeXL;
    private javax.swing.JButton btnWhite;
    private javax.swing.JLabel iconUSER;
    private javax.swing.JLabel iconUniversity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txtAccount;
    private javax.swing.JLabel txtAmount;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JLabel txtGlass;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtProduct;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtSize;
    private javax.swing.JLabel txtUSER;
    // End of variables declaration//GEN-END:variables

}
