/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bumarket.bumarket;

import java.awt.*;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author chait
 */
public class Register extends javax.swing.JFrame {
    
    private final UserData userdata;
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        userdata = new UserData();
        eye_hide.setVisible(false);
        eye_hide2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        RegisterBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SignInBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtUser = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        txtConfirmPass = new javax.swing.JPasswordField();
        eye_hide = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        eye_hide2 = new javax.swing.JLabel();
        eye1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Page");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(202, 202, 202));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterBtn.setBackground(new java.awt.Color(0, 0, 0));
        RegisterBtn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("Register");
        RegisterBtn.setToolTipText("");
        RegisterBtn.setRequestFocusEnabled(false);
        RegisterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterBtnMouseClicked(evt);
            }
        });
        jPanel3.add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 283, 203, 56));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(119, 119, 119));
        jLabel3.setText("Already A Member?");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 351, -1, -1));

        SignInBtn.setBackground(new java.awt.Color(208, 204, 204));
        SignInBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SignInBtn.setForeground(new java.awt.Color(255, 153, 0));
        SignInBtn.setText("Sign In");
        SignInBtn.setBorder(null);
        SignInBtn.setRequestFocusEnabled(false);
        SignInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInBtnMouseClicked(evt);
            }
        });
        jPanel3.add(SignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 351, -1, -1));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 279, -1, -1));

        txtLName.setBackground(new java.awt.Color(202, 202, 202));
        txtLName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLName.setForeground(new java.awt.Color(119, 119, 119));
        txtLName.setText("Last Name");
        txtLName.setBorder(null);
        txtLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLNameFocusLost(evt);
            }
        });
        jPanel3.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 105, 252, -1));

        txtId.setBackground(new java.awt.Color(202, 202, 202));
        txtId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(119, 119, 119));
        txtId.setText("Student ID");
        txtId.setBorder(null);
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 15, 252, -1));

        txtFName.setBackground(new java.awt.Color(202, 202, 202));
        txtFName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFName.setForeground(new java.awt.Color(119, 119, 119));
        txtFName.setText("First Name");
        txtFName.setBorder(null);
        txtFName.setCaretPosition(9);
        txtFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFNameFocusLost(evt);
            }
        });
        jPanel3.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 60, 252, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 252, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 83, 252, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 128, 252, 10));

        txtUser.setBackground(new java.awt.Color(202, 202, 202));
        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(119, 119, 119));
        txtUser.setText("Username");
        txtUser.setBorder(null);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        jPanel3.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 150, 252, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 171, 252, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 213, 252, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 255, 252, 10));

        txtPass.setBackground(new java.awt.Color(202, 202, 202));
        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(119, 119, 119));
        txtPass.setText("Password");
        txtPass.setBorder(null);
        txtPass.setEchoChar('\u0000');
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        jPanel3.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 190, 226, -1));

        txtConfirmPass.setBackground(new java.awt.Color(202, 202, 202));
        txtConfirmPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtConfirmPass.setForeground(new java.awt.Color(119, 119, 119));
        txtConfirmPass.setText("Confirm Password");
        txtConfirmPass.setBorder(null);
        txtConfirmPass.setEchoChar('\u0000');
        txtConfirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPassFocusLost(evt);
            }
        });
        jPanel3.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 229, 226, -1));

        eye_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png"))); // NOI18N
        eye_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eye_hideMousePressed(evt);
            }
        });
        jPanel3.add(eye_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 187, -1, -1));

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eyeMousePressed(evt);
            }
        });
        jPanel3.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 187, -1, -1));

        eye_hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png"))); // NOI18N
        eye_hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eye_hide2MousePressed(evt);
            }
        });
        jPanel3.add(eye_hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 229, -1, -1));

        eye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png"))); // NOI18N
        eye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eye1MousePressed(evt);
            }
        });
        jPanel3.add(eye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 229, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, 380));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("BU MARKET");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2.2.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 160, 140));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("WELCOME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInBtnMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignInBtnMouseClicked

    private void RegisterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMouseClicked
        String username = txtUser.getText().trim();
        String password = String.valueOf(txtPass.getPassword()).trim();
        String fname = txtFName.getText().trim();
        String lname = txtLName.getText().trim();
        String id = txtId.getText().trim();
        String confirm_pwd = String.valueOf(txtConfirmPass.getPassword()).trim();
        try {
            File file = new File("account.txt");
            FileWriter fw = new FileWriter(file, true);
            if(username.equals("Username") || password.equals("Password") || fname.equals("First Name") || lname.equals("Last Name") || id.equals("Student ID")) {
                JOptionPane.showMessageDialog(this, "One or Both fields are empty", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else {
                if(password.equals(confirm_pwd)) {
                    userdata.getUsers();
                    if(!userdata.checkIfUseridExist(id)) {
                        if(!id.matches("[0-9]+") || id.length() < 10 || id.length() > 10) {
                            JOptionPane.showMessageDialog(this, "Student ID must contains only numbers and have only 10 digits", "Warning", JOptionPane.WARNING_MESSAGE);
                            txtId.requestFocus();
                        }
                        else {
                            if(userdata.checkPasswordStrength(password) == 3) {
                                if(!fname.matches("[A-Za-z]+") || !lname.matches("[A-Za-z]+")) {
                                    JOptionPane.showMessageDialog(this, "Firstname and Lastname must contains only letters", "Warning", JOptionPane.WARNING_MESSAGE);
                                    txtFName.requestFocus();
                                }
                                else {
                                    if(!userdata.checkIfUsernameExist(username)) {
                                        fw.write(System.getProperty("line.separator"));
                                        fw.write("Username: " + username);
                                        fw.write(System.getProperty("line.separator"));
                                        fw.write("Firstname: " + fname.substring(0,1).toUpperCase() + fname.substring(1).toLowerCase());
                                        fw.write(System.getProperty("line.separator"));
                                        fw.write("Lastname: " + lname.substring(0,1).toUpperCase() + lname.substring(1).toLowerCase());
                                        fw.write(System.getProperty("line.separator"));
                                        fw.write("Password: " + password);
                                        fw.write(System.getProperty("line.separator"));
                                        fw.write("Student ID: " + id);
                                        fw.write(System.getProperty("line.separator"));
                                        fw.close();

                                        JOptionPane.showMessageDialog(this, "Register Successfully", "Info", JOptionPane.INFORMATION_MESSAGE);
                                        new Login().setVisible(true);
                                        this.dispose();
                                    }
                                    else {
                                        JOptionPane.showMessageDialog(this, "This Username Already Exist, Try Another One", "Warning", JOptionPane.WARNING_MESSAGE);
                                        txtUser.requestFocus();
                                    } 
                                }
                            }
                            else {
                                JOptionPane.showMessageDialog(this, "Password must longer than 8 chars and contains special characters", "Warning", JOptionPane.WARNING_MESSAGE);
                                txtPass.requestFocus();
                            }
                        }
                    }
                    else {
                       JOptionPane.showMessageDialog(this, "This Student Id Already Exist", "Warning", JOptionPane.WARNING_MESSAGE);
                       txtId.requestFocus();
                    }
                }
                else {
                    JOptionPane.showMessageDialog(this, "Password Doesn't Match", "Warning", JOptionPane.WARNING_MESSAGE);
                    txtConfirmPass.requestFocus();
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Failed to Register", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Failed to Register", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterBtnMouseClicked

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
        if(txtId.getText().equals("Student ID"))
       {
           txtId.setText("");
       }
    }//GEN-LAST:event_txtIdFocusGained

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        if (txtId.getText().length()==0)
            txtId.setText("Student ID");
    }//GEN-LAST:event_txtIdFocusLost

    private void txtFNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFNameFocusGained
        if(txtFName.getText().equals("First Name"))
       {
           txtFName.setText("");
       }
    }//GEN-LAST:event_txtFNameFocusGained

    private void txtFNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFNameFocusLost
        if (txtFName.getText().length()==0)
            txtFName.setText("First Name");
    }//GEN-LAST:event_txtFNameFocusLost

    private void txtLNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLNameFocusLost
        if (txtLName.getText().length()==0)
            txtLName.setText("Last Name");
    }//GEN-LAST:event_txtLNameFocusLost

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if (txtUser.getText().length()==0)
            txtUser.setText("Username");
    }//GEN-LAST:event_txtUserFocusLost

    private void txtLNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLNameFocusGained
        if(txtLName.getText().equals("Last Name"))
       {
           txtLName.setText("");
       }
    }//GEN-LAST:event_txtLNameFocusGained

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        if(txtUser.getText().equals("Username"))
       {
           txtUser.setText("");
       }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        if(txtPass.getText().equals("Password"))
       {
           txtPass.setText("");
       }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtConfirmPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPassFocusGained
        if(txtConfirmPass.getText().equals("Confirm Password"))
       {
           txtConfirmPass.setText("");
       }
    }//GEN-LAST:event_txtConfirmPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        if (txtPass.getText().length()==0)
            txtPass.setText("Password");
    }//GEN-LAST:event_txtPassFocusLost

    private void txtConfirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPassFocusLost
        if (txtConfirmPass.getText().length()==0)
            txtConfirmPass.setText("Confirm Password");
    }//GEN-LAST:event_txtConfirmPassFocusLost

    private void eye_hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_hideMousePressed
        eye_hide.setVisible(false);
        eye.setVisible(true);
        txtPass.setEchoChar((char)0);
    }//GEN-LAST:event_eye_hideMousePressed

    private void eyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMousePressed
        eye.setVisible(false);
        eye_hide.setVisible(true);
        txtPass.setEchoChar('*');
    }//GEN-LAST:event_eyeMousePressed

    private void eye_hide2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_hide2MousePressed
        eye_hide2.setVisible(false);
        eye1.setVisible(true);
        txtConfirmPass.setEchoChar((char)0);
    }//GEN-LAST:event_eye_hide2MousePressed

    private void eye1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye1MousePressed
        eye1.setVisible(false);
        eye_hide2.setVisible(true);
        txtConfirmPass.setEchoChar('*');
    }//GEN-LAST:event_eye1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel eye1;
    private javax.swing.JLabel eye_hide;
    private javax.swing.JLabel eye_hide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
